[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
fuzz_runs = 1000
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@chainlink/=node_modules/@chainlink/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/=node_modules/@rari-capital/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
gas_reports = ["*"]
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config